name: flutter_scripts
description: "Collaborative Scripts Platform"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^0.13.6  # Versión reducida para compatibilidad con flutter_code_editor
  intl: ^0.19.0
  path: ^1.9.1
  crypto: ^3.0.6
  file_picker: ^6.2.1
  path_provider: ^2.1.5
  mysql1: ^0.20.0
  process_run: ^0.13.3+1
  qr_flutter: ^4.1.0
  otp: ^3.1.4
  flutter_syntax_view: ^4.1.7
  flutter_highlight: ^0.7.0
  window_manager: ^0.3.9
  flutter_acrylic: ^1.1.4
  
  # Nuevas dependencias para mejoras de escritorio
  split_view: ^3.2.1
  desktop_drop: ^0.4.1
  flutter_code_editor: ^0.2.12
  highlight: ^0.7.0
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  
  # Puedes añadir aquí tus assets, fonts, etc.