import 'package:flutter/material.dart';

class LocalizationProvider extends ChangeNotifier {
  String _currentLocale = 'es';
  
  String get currentLocale => _currentLocale;
  
  void toggleLocale() {
    _currentLocale = _currentLocale == 'es' ? 'en' : 'es';
    notifyListeners();
  }
  
  String getText(String key) {
    return _localizationMap[_currentLocale]?[key] ?? key;
  }
  
  final Map<String, Map<String, String>> _localizationMap = {
    'es': {
      'title': 'Plataforma de Scripts Colaborativos',
      'login': 'Iniciar Sesión',
      'register': 'Registro',
      'scripts': 'Scripts',
      'admin': 'Administración',
      'history': 'Historial',
      'execute': 'Ejecutar',
      'stats': 'Estadísticas',
      'refresh': 'Actualizar',
      'upload': 'Subir Script',
      'download': 'Descargar',
      'delete_all': 'Eliminar Todo',
      'delete_selected': 'Eliminar Seleccionado',
      'approve': 'Aprobar',
      'delete_user': 'Eliminar',
      'export': 'Exportar',
      'save': 'Guardar',
      'preview': 'Vista Previa',
      'theme': 'Cambiar Tema',
      'language': 'Cambiar Idioma',
      'logout': 'Cerrar Sesión',
      'status_ready': 'Listo',
      'status_loading': 'Cargando...',
      'warning': 'Advertencia',
      'complete_fields': 'Complete todos los campos (Usuario: mín. 3 caracteres, Contraseña: mín. 6 caracteres)',
      'pending_approval': 'Cuenta pendiente de aprobación',
      'invalid_credentials': 'Credenciales incorrectas',
      'success': 'Éxito',
      'register_success': 'Registro exitoso. Escanea el código QR con Google Authenticator y espera aprobación.',
      'script_uploaded': 'Script subido correctamente',
      'script_downloaded': 'Script descargado correctamente',
      'script_saved': 'Script guardado correctamente',
      'script_deleted': 'Scripts eliminados',
      'user_approved': 'Usuario aprobado: {username}',
      'user_deleted': 'Usuario eliminado: {username}',
      'history_exported': 'Historial exportado correctamente',
      'no_script': 'No hay script para ejecutar',
      'select_script': 'Seleccione un script primero',
      'unsafe_script': 'El script contiene comandos potencialmente peligrosos. ¿Ejecutar de todos modos?',
      'executing': 'Ya hay un script en ejecución',
      'empty_script': 'El script está vacío',
      'select_user': 'Seleccione un usuario',
      'confirm_delete_scripts': '¿Eliminar todos los scripts?',
      'confirm_delete_script': '¿Eliminar el script seleccionado?',
      'confirm_delete_user': '¿Eliminar usuario {username}?',
      'toggle_role': 'Cambiar Rol',
      'totp_required': 'Debe ingresar el código TOTP',
      'totp_invalid': 'Código TOTP incorrecto',
      'chatbot_title': 'Chatbot DeepSeek',
      'enviar': 'Enviar',
      'limpiar_chat': 'Limpiar Chat',
      'placeholder_chat': 'Escribe tu consulta aquí...',
      'password': 'Contraseña',
      'username': 'Usuario',
      'min_chars_user': 'Mínimo 3 caracteres',
      'min_chars_pass': 'Mínimo 6 caracteres',
      'enter_code': 'Ingrese el código TOTP',
      'created_by': 'Creado Por PedroMiguel && Eloy Ramirez Revuelta',
      'search': 'Buscar',
      'by': 'Por',
      'back': 'Volver',
      'totp_code': 'Código TOTP',
      'scan_qr': 'Escanea este código QR con Google Authenticator',
      'errors': 'Errores',
      'critical_error': 'Error crítico',
      'success_msg': 'Éxito',
      'executing_msg': 'Ejecutando...',
      'uploaded': 'Subido',
      'modified': 'Modificado',
      'last_execution': 'Última ejecución',
      'executed': 'Ejecutado',
      'downloaded': 'Descargado',
      'times': 'veces',
      'never': 'Nunca',
      'confirm': 'Confirmar',
    },
    'en': {
      'title': 'Collaborative Scripts Platform',
      'login': 'Log In',
      'register': 'Register',
      'scripts': 'Scripts',
      'admin': 'Administration',
      'history': 'History',
      'execute': 'Execute',
      'stats': 'Statistics',
      'refresh': 'Refresh',
      'upload': 'Upload Script',
      'download': 'Download',
      'delete_all': 'Delete All',
      'delete_selected': 'Delete Selected',
      'approve': 'Approve',
      'delete_user': 'Delete',
      'export': 'Export',
      'save': 'Save',
      'preview': 'Preview',
      'theme': 'Change Theme',
      'language': 'Change Language',
      'logout': 'Log Out',
      'status_ready': 'Ready',
      'status_loading': 'Loading...',
      'warning': 'Warning',
      'complete_fields': 'Complete all fields (Username: min. 3 characters, Password: min. 6 characters)',
      'pending_approval': 'Account pending approval',
      'invalid_credentials': 'Invalid credentials',
      'success': 'Success',
      'register_success': 'Registration successful. Scan the QR code with Google Authenticator and wait for approval.',
      'script_uploaded': 'Script uploaded successfully',
      'script_downloaded': 'Script downloaded successfully',
      'script_saved': 'Script saved successfully',
      'script_deleted': 'Scripts deleted',
      'user_approved': 'User approved: {username}',
      'user_deleted': 'User deleted: {username}',
      'history_exported': 'History exported successfully',
      'no_script': 'No script to execute',
      'select_script': 'Select a script first',
      'unsafe_script': 'The script contains potentially dangerous commands. Execute anyway?',
      'executing': 'A script is already executing',
      'empty_script': 'The script is empty',
      'select_user': 'Select a user',
      'confirm_delete_scripts': 'Delete all scripts?',
      'confirm_delete_script': 'Delete selected script?',
      'confirm_delete_user': 'Delete user {username}?',
      'toggle_role': 'Toggle Role',
      'totp_required': 'You must enter the TOTP code',
      'totp_invalid': 'Invalid TOTP code',
      'chatbot_title': 'DeepSeek Chatbot',
      'enviar': 'Send',
      'limpiar_chat': 'Clear Chat',
      'placeholder_chat': 'Type your query here...',
      'password': 'Password',
      'username': 'Username',
      'min_chars_user': 'Minimum 3 characters',
      'min_chars_pass': 'Minimum 6 characters',
      'enter_code': 'Enter TOTP code',
      'created_by': 'Created By PedroMiguel && Eloy Ramirez Revuelta',
      'search': 'Search',
      'by': 'By',
      'back': 'Back',
      'totp_code': 'TOTP Code',
      'scan_qr': 'Scan this QR code with Google Authenticator',
      'errors': 'Errors',
      'critical_error': 'Critical Error',
      'success_msg': 'Success',
      'executing_msg': 'Executing...',
      'uploaded': 'Uploaded',
      'modified': 'Modified',
      'last_execution': 'Last execution',
      'executed': 'Executed',
      'downloaded': 'Downloaded',
      'times': 'times',
      'never': 'Never',
      'confirm': 'Confirm',
    }
  };
}